language: node_js

node_js:
  - "8"

before_install:
  - npm i -g npm@6

install:
  - npm install

script:
  - npm run cover
  - npm run build

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'
